import React from 'react';
import { ControlProps, EnumCellProps, RankedTester, rankWith, WithClassname } from '@jsonforms/core';

import { TranslateProps, withJsonFormsControlProps, withTranslateProps } from '@jsonforms/react';
import { MaterialInputControl } from "@jsonforms/material-renderers";
import { parentSchemaMatches } from "../testers/ParentSchemaMatches";
import { MuiIconSelect } from "../mui-controls/MuiIconSelect";

const linearIconKeys = [
    "home",
    "apartment",
    "pencil",
    "magic-wand",
    "drop",
    "lighter",
    "poop",
    "sun",
    "moon",
    "cloud",
    "cloud-upload",
    "cloud-download",
    "cloud-sync",
    "cloud-check",
    "database",
    "lock",
    "cog",
    "trash",
    "dice",
    "heart",
    "star",
    "star-half",
    "star-empty",
    "flag",
    "envelope",
    "paperclip",
    "inbox",
    "eye",
    "printer",
    "file-empty",
    "file-add",
    "enter",
    "exit",
    "graduation-hat",
    "license",
    "music-note",
    "film-play",
    "camera-video",
    "camera",
    "picture",
    "book",
    "bookmark",
    "user",
    "users",
    "shirt",
    "store",
    "cart",
    "tag",
    "phone-handset",
    "phone",
    "pushpin",
    "map-marker",
    "map",
    "location",
    "calendar-full",
    "keyboard",
    "spell-check",
    "screen",
    "smartphone",
    "tablet",
    "laptop",
    "laptop-phone",
    "power-switch",
    "bubble",
    "heart-pulse",
    "construction",
    "pie-chart",
    "chart-bars",
    "gift",
    "diamond",
    "linearicons",
    "dinner",
    "coffee-cup",
    "leaf",
    "paw",
    "rocket",
    "briefcase",
    "bus",
    "car",
    "train",
    "bicycle",
    "wheelchair",
    "select",
    "earth",
    "smile",
    "sad",
    "neutral",
    "mustache",
    "alarm",
    "bullhorn",
    "volume-high",
    "volume-medium",
    "volume-low",
    "volume",
    "mic",
    "hourglass",
    "undo",
    "redo",
    "sync",
    "history",
    "clock",
    "download",
    "upload",
    "enter-down",
    "exit-up",
    "bug",
    "code",
    "link",
    "unlink",
    "thumbs-up",
    "thumbs-down",
    "magnifier",
    "cross",
    "menu",
    "list",
    "chevron-up",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "arrow-up",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "move",
    "warning",
    "question-circle",
    "menu-circle",
    "checkmark-circle",
    "cross-circle",
    "plus-circle",
    "circle-minus",
    "arrow-up-circle",
    "arrow-down-circle",
    "arrow-left-circle",
    "arrow-right-circle",
    "chevron-up-circle",
    "chevron-down-circle",
    "chevron-left-circle",
    "chevron-right-circle",
    "crop",
    "frame-expand",
    "frame-contract",
    "layers",
    "funnel",
    "text-format",
    "text-format-remove",
    "text-size",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "highlight",
    "text-align-left",
    "text-align-center",
    "text-align-right",
    "text-align-justify",
    "line-spacing",
    "indent-increase",
    "indent-decrease",
    "pilcrow",
    "direction-ltr",
    "direction-rtl",
    "page-break",
    "sort-alpha-asc",
    "sort-amount-asc",
    "hand",
    "pointer-up",
    "pointer-right",
    "pointer-down",
    "pointer-left"
];

export const SelectLinearIconsControl = (props: ControlProps & EnumCellProps & WithClassname & TranslateProps) => {

    let props_new: ControlProps & EnumCellProps & TranslateProps = {
        options: linearIconKeys
            .map(key => ({
                    label: key,
                    value: key
                })
            ),
        ...props
    }
    return <MaterialInputControl
                {...props_new}
                input={MuiIconSelect}
            />
};

export const SelectLinearIconsControlTester: RankedTester = rankWith(
    20,
    parentSchemaMatches((schema, currentDataSchema) => {
        return (schema.title == "LinearIcon" && currentDataSchema.title == "Name");
    })
);

export default withJsonFormsControlProps(withTranslateProps(SelectLinearIconsControl));
